pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "../config" as Config

// The editable half of the keybinds.
//
// Nothing here rewrites hyprland.lua. That file is hand-written, carries
// comments and logic, and a settings window that regenerated it would throw
// all of that away the first time you changed a shortcut. Instead the shell
// owns a second file — ~/.config/hypr/binds.lua — which hyprland.lua reads at
// the end of its own run, so whatever is in here wins over the defaults
// above it without touching them.
//
// The shortcuts themselves persist in theme.json as a key → accelerator map,
// so binds.lua can be regenerated from scratch at any time and is never the
// source of truth.
Singleton {
    id: root

    readonly property string hyprDir: (Quickshell.env("XDG_CONFIG_HOME")
                                       || (Quickshell.env("HOME") + "/.config")) + "/hypr"

    // Everything the shell exposes, with the default Hyprland writes when
    // nothing has been customised. `ipc` is the IpcHandler function in
    // shell.qml; `dispatch` is a raw Hyprland dispatcher instead.
    readonly property var actions: [
        { key: "launcher",    n: "Open launcher",        def: "SUPER + SPACE",     ipc: "toggleLauncher" },
        { key: "overview",    n: "Overview",             def: "SUPER + Tab",       ipc: "toggleOverview" },
        { key: "control",     n: "Control center",       def: "SUPER + C",         ipc: "toggleControlCenter" },
        { key: "notes",       n: "Notification center",  def: "SUPER + N",         ipc: "toggleNotifications" },
        { key: "dnd",         n: "Toggle do not disturb", def: "SUPER + SHIFT + N", ipc: "toggleDnd" },
        { key: "settings",    n: "Open settings",        def: "SUPER + comma",     ipc: "openSettings" },
        { key: "theme",       n: "Toggle theme",         def: "SUPER + SHIFT + T", ipc: "toggleTheme" },
        { key: "reload",      n: "Reload shell",         def: "SUPER + SHIFT + R", ipc: "reloadShell" },
        { key: "lock",        n: "Lock screen",          def: "SUPER + L",         ipc: "lock" },
        { key: "showdesktop", n: "Show desktop",         def: "SUPER + D",         ipc: "showDesktop" },
        { key: "terminal",    n: "Terminal",             def: "SUPER + Return",    exec: "terminal" },
        { key: "files",       n: "File manager",         def: "SUPER + E",         exec: "files" },
        { key: "browser",     n: "Browser",              def: "SUPER + B",         exec: "browser" },
        { key: "close",       n: "Close window",         def: "SUPER + Q",         dispatch: "killactive" },
        { key: "float",       n: "Toggle floating",      def: "SUPER + V",         dispatch: "togglefloating" },
        { key: "fullscreen",  n: "Fullscreen",           def: "SUPER + F",         dispatch: "fullscreen 0" }
    ]

    // key → accelerator, for anything changed from its default.
    function overrides() {
        if (!Config.Appearance.keybinds) return ({});
        try {
            const o = JSON.parse(Config.Appearance.keybinds);
            return (o && typeof o === "object") ? o : ({});
        } catch (e) {
            console.warn("Keybinds: theme.json keybinds is not valid JSON —", e);
            return ({});
        }
    }

    function accelFor(key) {
        const o = overrides();
        if (o[key]) return o[key];
        const a = actions.find(x => x.key === key);
        return a ? a.def : "";
    }

    function isCustom(key) { return !!overrides()[key]; }

    function setAccel(key, accel) {
        const o = overrides();
        const a = actions.find(x => x.key === key);
        if (!a) return;
        if (!accel || accel === a.def) delete o[key];
        else o[key] = accel;
        Config.Appearance.keybinds = JSON.stringify(o);
        write();
    }

    function resetAll() {
        Config.Appearance.keybinds = "";
        write();
    }

    // ── generated file ────────────────────────────────────────────────────
    FileView {
        id: bindsFile
        path: root.hyprDir + "/binds.lua"
        preload: true
        printErrors: false
        atomicWrites: true
    }

    Process { id: reloadProc }

    function luaStr(s) {
        return '"' + String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
    }

    function body() {
        const shellCall = f =>
            "hl.dsp.exec_cmd(" + luaStr("qs -c hyprshell ipc call shell " + f) + ")";
        const lines = [
            "-- Generated by the shell's Settings → Keybinds. Do not hand-edit:",
            "-- it is rewritten whenever a shortcut changes.",
            "--",
            "-- hyprland.lua reads this at the end of its own run, so anything here",
            "-- replaces the default above it. Delete the file to go back to those.",
            "",
            "local apps = { terminal = " + luaStr(Config.Apps.execFor("appTerm"))
                + ", files = " + luaStr(Config.Apps.execFor("appFiles"))
                + ", browser = " + luaStr(Config.Apps.execFor("appWeb")) + " }",
            ""
        ];
        for (let i = 0; i < actions.length; i++) {
            const a = actions[i];
            const accel = accelFor(a.key);
            if (!accel) continue;
            let d;
            if (a.ipc) d = shellCall(a.ipc);
            else if (a.exec) d = "hl.dsp.exec_cmd(apps." + a.exec + ")";
            else d = "hl.dsp.exec_cmd(" + luaStr("hyprctl dispatch " + a.dispatch) + ")";
            lines.push("hl.bind(" + luaStr(accel) + ", " + d + ")   -- " + a.n);
        }
        return lines.join("\n") + "\n";
    }

    function write() {
        bindsFile.setText(body());
        // Hyprland only reads binds at config load, so the file is inert
        // until a reload. The shell re-applies its runtime settings after.
        reloadProc.running = false;
        reloadProc.command = ["hyprctl", "reload"];
        reloadProc.running = true;
    }
}
